server:
  port: 80
spring:
  cloud:
    client:
       ip-address: 10.1.2.98
  redis:
    host: 10.1.2.98
    password: 123456
zuul:
  routes:
    sdas-protal:
      path: /**
      url: http://10.1.2.98:15001
sdas:
  eureka:
    server:
      host: 10.1.2.98
      port: 11010
      user: lixuroot
      password: lx123456