server:
  port: 80
spring:
  cloud:
    client:
       ip-address: 172.17.235.158
  redis:
    host: 172.17.235.158
    password: 123456
zuul:
  routes:
    sdas-protal:
      path: /**
      url: http://172.17.235.158:15001
sdas:
  eureka:
    server:
      host: 172.17.235.158
      port: 11010
      user: lixuroot
      password: 123456