server:
  port: 11039
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    basedir: /tmp/tomcat/${spring.application.name}
spring:
  application:
    name: sdas-gateway
  profiles:
    active: default
  main:
    bannerMode: "off"
  http:
     encoding:
       charset: UTF-8
       enabled: true
       force: true
  servlet:
     multipart:
       enabled: true
       file-size-threshold: 0
       max-file-size: 100000Mb
       max-request-size: 100000Mb
  cloud:
    client:
      ip-address: 127.0.0.1
  redis:
    database: 0
    host: 192.168.10.130
    port: 6370
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 128
        max-wait: -1
        max-idle: 8
        min-idle: 2
eureka:
  instance:
    #hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true
    ip-address: ${spring.cloud.client.ip-address}
    leaseExpirationDurationInSeconds: 40
    leaseRenewalIntervalInSeconds: 5
    registryFetchIntervalSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${sdas.eureka.server.user}:${sdas.eureka.server.password}@${sdas.eureka.server.host}:${sdas.eureka.server.port}/eureka
zuul:
  sensitiveHeaders: 
  addHostHeader: true
  retryable: true
  host:
    maxTotalConnections: 2000
    maxPerRouteConnections: 20
  semaphore:
    max-semaphores: 128
  routes:
    fdfs-service:
      path: /fdfs/**
      url: http://192.168.10.131
    sdas-protal:
      path: /**
      url: http://127.0.0.1
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 1000000
  maxAutoRetries: 2
  maxAutoRetriesNextServer: 2
  okToRetryOnAllOperations: true
hystrix:
  command:
    default:
      fallback: 
        enabled: true
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
      requestCache:
        enabled: true
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 4000000
logging:
  config: classpath:logback.xml
  
#======================================#
#========== Project settings ==========#
#======================================#
sdas:
  eureka:
    server:
      host: 127.0.0.1
      port: 11010
      user: lixu
      password: 123456
  #模拟开关 YES/NO
  mockenable: NO
  user-mgnt-service-name: sdas-module-user-mgnt
  toPortal: true
  protal-login-url: view/login/login.html
  protal-personal-url-prefix: /view/personal
  protal-name: portal
  swagger-uris: /admin/login,/webjars/springfox-swagger-ui/fonts/DroidSans.ttf,/swagger-resources/configuration/ui,/swagger-resources,/v2/api-docs,/servlet/validateCodeServlet
  static-subfixes: .css,.js,.png,.jpg,.gif,.jpeg,.bmp,.ico,.swf,.psd,.htc,.htm,.html,.crx,.xpi,.exe,.ipa,.apk,.tff,.zz,.do,.json,.otf,.eot,.svg,.ttf,.woff,.woff2
  asdp-app-name: asdp
  ssns-service-name: sdas-module-ssns
  scs-service-name: sdas-module-scs
  asdp-permit-uris: /${sdas.asdp-app-name}/,/${sdas.asdp-app-name}/login.htm,/${sdas.asdp-app-name}/user/forgetPassword.htm,/${sdas.asdp-app-name}/user/register/sendSms.htm,/${sdas.asdp-app-name}/user/readMessage.htm,/${sdas.asdp-app-name}/institute/register/sendSms.htm,/${sdas.asdp-app-name}/institute/register/downloadTemplate.htm,/${sdas.asdp-app-name}/institute/regHint.htm,/${sdas.asdp-app-name}/user/register/checkVerifyCode.htm,/${sdas.asdp-app-name}/user/register/checkImageVerifyCode.htm,/${sdas.asdp-app-name}/user/register/findByProvinceId.htm,/${sdas.asdp-app-name}/common/servlet/validateCodeServlet,/${sdas.asdp-app-name}/instituteRegistration.htm,/${sdas.asdp-app-name}/registrateInstitute.htm,/${sdas.asdp-app-name}/userRegistration.htm,/${sdas.asdp-app-name}/registrateUser.htm,/${sdas.asdp-app-name}/error,/${sdas.asdp-app-name}/noerror,/${sdas.asdp-app-name}/noerrornoview,/${sdas.asdp-app-name}/loginfailed.htm,/${sdas.asdp-app-name}/user/modifyPassword.htm,/${sdas.asdp-app-name}/user/checkCell.htm,/${sdas.asdp-app-name}/user/checkCellRegistered.htm
  asdp-permit-prefix-uris: /${sdas.asdp-app-name}/web/,/${sdas.asdp-app-name}/resources/,/${sdas.ssns-service-name}/public,/${sdas.scs-service-name}/public
  static-cache-control: public,max-age=7200